#! /usr/bin/env perl
# Order-STM - Programed by Mauricio J Lozano
use strict;
use warnings;

#opens and loads the file resultados.txt generated by contar_firmas script line by line, and loads barcodes, inputs barcodes, pools and tag index into arrays.
open(ORDENAR, "<resultados.txt");
my @ordenar_a = <ORDENAR>;
close ORDENAR;


open (INPUT, "<input.txt");
my @inputs_a = <INPUT>;
close (INPUT);

#declare hash variables
my %ordenar_h;
my %inputs_h;
my %resultados_h;

%inputs_h = map {split(",", $_)} @inputs_a;
%ordenar_h = map {split(",", $_)} @ordenar_a;


foreach my $key (sort keys %ordenar_h){
	# For each key of ordenar_h, declares scalar variables which will be filled with parts of the condition_pool_RE_mutant-tag index.
	chomp ($ordenar_h{$key});	
	my $key_c = $key;
	my $key_hok = $key;	
	my $key_p = $key;
	my $key_f = $key;
	$key_c =~ s/R.*//i;									#condition
	$key_hok =~ s/.*(-\w).*/$1/i;								#RE h o k
	$key_p =~ s/.*(POOL\d*)_\d*/$1/;							#pool
	$key_f =~ s/.*_.*_(\d*)/$1/i;								#mutant-tag
	
	if (exists $resultados_h{$key_c.$key_hok."_".$key_p."_".$key_f}){
		$resultados_h{$key_c.$key_hok."_".$key_p."_".$key_f} = $resultados_h{$key_c.$key_hok."_".$key_p."_".$key_f}.",".$ordenar_h{$key};
	}
	else {
		$resultados_h{$key_c.$key_hok."_".$key_p."_".$key_f} = $ordenar_h{$key};
	}
		
}


# write two files with the input and output results

my %resultados_input_h;
my %resultados_output_h;

# loads hash element by element and separates input from output conditions.
foreach my $key_res (keys %resultados_h){
	my $verificador = 0;
	foreach my $key_in (keys %inputs_h){
		$key_in =~ s/R.*//i;
		if ($key_res =~ /$key_in/){
			$resultados_input_h{$key_res} = $resultados_h{$key_res};
			$verificador = 1;
			last;
		}
	}	
	if ($verificador == 0){
	$resultados_output_h{$key_res} = $resultados_h{$key_res};
	}
}

open (RESULTADOSI,">resultados_inputs.txt");
foreach my $key_r (keys %resultados_input_h){
	print RESULTADOSI $key_r.",".$resultados_input_h{$key_r}."\n";
	}
close RESULTADOSI;

open (RESULTADOSO,">resultados_outputs.txt");
foreach my $key_r (keys %resultados_output_h){
	print RESULTADOSO $key_r.",".$resultados_output_h{$key_r}."\n";
	}
close RESULTADOSO;
